/**
 * PDF Generation Service
 * Generates PDFs for prescriptions, reports, and invoices
 */

export interface PDFOptions {
  title?: string;
  author?: string;
  subject?: string;
  keywords?: string[];
}

class PDFService {
  /**
   * Generate PDF from HTML content
   * Uses browser's print functionality for PDF generation
   */
  generatePDFFromHTML(htmlContent: string, filename: string, options?: PDFOptions): void {
    // Create a new window with the HTML content
    const printWindow = window.open('', '_blank');
    if (!printWindow) {
      console.error('Unable to open print window. Please allow popups.');
      return;
    }

    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
        <head>
          <title>${options?.title || filename}</title>
          <style>
            @media print {
              @page {
                size: A4;
                margin: 1cm;
              }
              body {
                margin: 0;
                padding: 0;
              }
            }
            body {
              font-family: Arial, sans-serif;
              line-height: 1.6;
              color: #333;
              max-width: 800px;
              margin: 0 auto;
              padding: 20px;
            }
            .header {
              border-bottom: 2px solid #0066CC;
              padding-bottom: 10px;
              margin-bottom: 20px;
            }
            .footer {
              border-top: 1px solid #ddd;
              padding-top: 10px;
              margin-top: 20px;
              text-align: center;
              font-size: 12px;
              color: #666;
            }
            table {
              width: 100%;
              border-collapse: collapse;
              margin: 20px 0;
            }
            th, td {
              border: 1px solid #ddd;
              padding: 12px;
              text-align: left;
            }
            th {
              background-color: #0066CC;
              color: white;
            }
            .prescription-header {
              text-align: center;
              margin-bottom: 30px;
            }
            .prescription-details {
              margin: 20px 0;
            }
            .prescription-item {
              margin: 15px 0;
              padding: 10px;
              background-color: #f9f9f9;
              border-left: 4px solid #0066CC;
            }
            .signature-section {
              margin-top: 40px;
              display: flex;
              justify-content: space-between;
            }
            .signature-box {
              width: 200px;
              border-top: 1px solid #333;
              padding-top: 10px;
              text-align: center;
            }
          </style>
        </head>
        <body>
          ${htmlContent}
          <div class="footer">
            Generated by NexaFya Health Platform • ${new Date().toLocaleString()}
          </div>
        </body>
      </html>
    `);

    printWindow.document.close();

    // Wait for content to load, then print
    printWindow.onload = () => {
      setTimeout(() => {
        printWindow.print();
        // Optionally close after printing
        // printWindow.close();
      }, 250);
    };
  }

  /**
   * Generate prescription PDF
   */
  generatePrescriptionPDF(prescription: any, doctorName: string, patientName: string): void {
    const htmlContent = `
      <div class="prescription-header">
        <h1>NexaFya Health Platform</h1>
        <h2>Medical Prescription</h2>
      </div>

      <div class="prescription-details">
        <p><strong>Patient:</strong> ${patientName}</p>
        <p><strong>Doctor:</strong> ${doctorName}</p>
        <p><strong>Date:</strong> ${new Date().toLocaleDateString()}</p>
        ${prescription.qrCode ? `<p><strong>Prescription ID:</strong> ${prescription.id}</p>` : ''}
      </div>

      <h3>Medications:</h3>
      ${prescription.items?.map((item: any, index: number) => `
        <div class="prescription-item">
          <p><strong>${index + 1}. ${item.medication}</strong></p>
          <p>Dosage: ${item.dosage}</p>
          <p>Frequency: ${item.frequency}</p>
          <p>Duration: ${item.duration}</p>
          ${item.instructions ? `<p>Instructions: ${item.instructions}</p>` : ''}
        </div>
      `).join('') || '<p>No medications prescribed.</p>'}

      ${prescription.notes ? `
        <div class="prescription-details">
          <h3>Doctor's Notes:</h3>
          <p>${prescription.notes}</p>
        </div>
      ` : ''}

      <div class="signature-section">
        <div class="signature-box">
          <p>Doctor's Signature</p>
          <p>${doctorName}</p>
        </div>
        <div class="signature-box">
          <p>Date</p>
          <p>${new Date().toLocaleDateString()}</p>
        </div>
      </div>

      ${prescription.qrCode ? `
        <div style="text-align: center; margin-top: 30px;">
          <p>QR Code for Verification:</p>
          <img src="${prescription.qrCodeUrl || ''}" alt="Prescription QR Code" style="max-width: 200px;" />
        </div>
      ` : ''}
    `;

    this.generatePDFFromHTML(htmlContent, `prescription_${prescription.id}.pdf`, {
      title: `Prescription - ${patientName}`,
      subject: 'Medical Prescription',
    });
  }

  /**
   * Generate invoice PDF
   */
  generateInvoicePDF(invoice: any): void {
    const htmlContent = `
      <div class="header">
        <h1>Invoice</h1>
        <p><strong>Invoice #:</strong> ${invoice.id || invoice.invoiceNumber}</p>
        <p><strong>Date:</strong> ${new Date(invoice.date || Date.now()).toLocaleDateString()}</p>
      </div>

      <div class="prescription-details">
        <p><strong>Customer:</strong> ${invoice.customerName || 'N/A'}</p>
        ${invoice.pharmacyName ? `<p><strong>Pharmacy:</strong> ${invoice.pharmacyName}</p>` : ''}
      </div>

      <table>
        <thead>
          <tr>
            <th>Item</th>
            <th>Quantity</th>
            <th>Price</th>
            <th>Total</th>
          </tr>
        </thead>
        <tbody>
          ${invoice.items?.map((item: any) => `
            <tr>
              <td>${item.name || item.itemName}</td>
              <td>${item.quantity}</td>
              <td>${invoice.currency || 'TZS'} ${item.price?.toLocaleString() || item.unitPrice?.toLocaleString()}</td>
              <td>${invoice.currency || 'TZS'} ${(item.total || (item.quantity * (item.price || item.unitPrice || 0))).toLocaleString()}</td>
            </tr>
          `).join('') || ''}
        </tbody>
        <tfoot>
          <tr>
            <td colspan="3" style="text-align: right; font-weight: bold;">Total:</td>
            <td style="font-weight: bold;">${invoice.currency || 'TZS'} ${invoice.total?.toLocaleString() || '0'}</td>
          </tr>
        </tfoot>
      </table>

      ${invoice.paymentMethod ? `
        <div class="prescription-details">
          <p><strong>Payment Method:</strong> ${invoice.paymentMethod}</p>
          <p><strong>Status:</strong> ${invoice.status || 'PAID'}</p>
        </div>
      ` : ''}
    `;

    this.generatePDFFromHTML(htmlContent, `invoice_${invoice.id}.pdf`, {
      title: `Invoice - ${invoice.id}`,
      subject: 'Invoice',
    });
  }

  /**
   * Generate report PDF
   */
  generateReportPDF(report: any): void {
    const htmlContent = `
      <div class="header">
        <h1>${report.title || 'Report'}</h1>
        <p><strong>Generated:</strong> ${new Date().toLocaleString()}</p>
        ${report.period ? `<p><strong>Period:</strong> ${report.period}</p>` : ''}
      </div>

      ${report.description ? `<p>${report.description}</p>` : ''}

      ${report.data ? `
        <table>
          <thead>
            <tr>
              ${report.headers?.map((header: string) => `<th>${header}</th>`).join('') || ''}
            </tr>
          </thead>
          <tbody>
            ${report.data.map((row: any[]) => `
              <tr>
                ${row.map((cell: any) => `<td>${cell}</td>`).join('')}
              </tr>
            `).join('')}
          </tbody>
        </table>
      ` : ''}

      ${report.summary ? `
        <div class="prescription-details" style="margin-top: 30px;">
          <h3>Summary</h3>
          ${Object.entries(report.summary).map(([key, value]) => `
            <p><strong>${key}:</strong> ${value}</p>
          `).join('')}
        </div>
      ` : ''}
    `;

    this.generatePDFFromHTML(htmlContent, `${report.title?.toLowerCase().replace(/\s+/g, '_') || 'report'}.pdf`, {
      title: report.title || 'Report',
      subject: 'Report',
    });
  }
}

export const pdfService = new PDFService();
export default pdfService;

